# Generated by Django 4.2 on 2023-07-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
