# Generated by Django 4.2 on 2023-07-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='poster',
            field=models.TextField(blank=True, null=True),
        ),
    ]
